### ISSUE TITLE
Implement --help command as command-line option

### ISSUE THREAD

**Issue by gfcwfzkm** [YaSuenag/SimpleCom#22]
First of all, thank you for this tool. I've been using it a lot since I have discovered it with my dev machines.

Occasionally I forget the command line arguments, that the tool accepts, and find myself typing in `--help` as argument, often used to get all supported arguments of a tool or program.

I think SimpleCom would benefit from the implementation of a `--help` argument, as one doesn't have to look it up on the web each time this way.

What do you think of this idea?
Thank you for your time.

**Comment by YaSuenag** [comment]
Thanks for your comment! I completely agree with you. I will do that.
However I want to refactor option processing, so I need time.

**Comment by YaSuenag** [comment]
I added `--help` to SimpleCom. It will be shipped in next release!
