### ISSUE TITLE
allow --log-file option to save the log to txt log file

### ISSUE THREAD

**Issue by heartacker** [YaSuenag/SimpleCom#33]
RT

**Comment by YaSuenag** [comment]
What is "RT"?

**Comment by heartacker** [comment]
as title 😄

**Comment by YaSuenag** [comment]
Ok, so do you want to save all of contents on the console to the file which is specified with `--log-file` like `screen` command on Linux?

**Comment by heartacker** [comment]
we just want to some the log for check after
and may be it is a useful feature

**Comment by YaSuenag** [comment]
Again, do you mean console log, right? I guess you want to log your operations and responses from peripheral.
SimpleCom can print debug log for itself, so I want to clarify the meaning of the "log".

**Comment by YaSuenag** [comment]
@heartacker 
I added `--log-file` to log all of chars on serial communication. You can set it on setup dialog or `--logfile [log file path]` command line option. Can you try it? Comments are welcome.

I also attached SimpleCom for the test. Please use it if you cannot build https://github.com/YaSuenag/SimpleCom/tree/dev/logging .

[SimpleCom.zip](https://github.com/YaSuenag/SimpleCom/files/13848262/SimpleCom.zip)

**Comment by heartacker** [comment]
> @heartacker 
> I added `--log-file` to log all of chars on serial communication. You can set it on setup dialog or `--logfile [log file path]` command line option. Can you try it? Comments are welcome.
> 
> I also attached SimpleCom for the test. Please use it if you cannot build https://github.com/YaSuenag/SimpleCom/tree/dev/logging .
> 
> [SimpleCom.zip](https://github.com/YaSuenag/SimpleCom/files/13848262/SimpleCom.zip)
> 

Thanks i will check it later， and should I input a full path of Log。

**Comment by YaSuenag** [comment]
> should I input a full path of Log。

It is not mandatory, but I recommend set full path.

**Comment by heartacker** [comment]
> @heartacker I added `--log-file` to log all of chars on serial communication. You can set it on setup dialog or `--logfile [log file path]` command line option. Can you try it? Comments are welcome.
> 
> I also attached SimpleCom for the test. Please use it if you cannot build https://github.com/YaSuenag/SimpleCom/tree/dev/logging .
> 
> [SimpleCom.zip](https://github.com/YaSuenag/SimpleCom/files/13848262/SimpleCom.zip)

it works, wonderful and thanks

**Comment by YaSuenag** [comment]
Thanks for your evaluation! I merged a PR for this issue (#34 ).

I will release this feature in a month if I do not hear any other issues/proposals.
