### ISSUE TITLE
how can we exit the simplecom in cli terminal

### ISSUE THREAD

**Issue by heartacker** [YaSuenag/SimpleCom#44]
hi, can we do this,
exit the terminal instead?
thanks

**Comment by YaSuenag** [comment]
Press F1 key, then you can see the dialog box whether you want to close serial connection or not.

**Comment by YaSuenag** [comment]
Can you accept my answer?
I will close this if I do not hear any further questions.

**Comment by YaSuenag** [comment]
F1 key might not work on your Windows. I've fixed in #49 . I will merge after some tests/fixes. It would be shipped in next version.
