### ISSUE TITLE
add version information To ui or cli 

### ISSUE THREAD

**Issue by heartacker** [YaSuenag/SimpleCom#46]
- UI
![image](https://github.com/YaSuenag/SimpleCom/assets/1876302/324f5114-1f4b-4ab3-98a0-d58d72476b04)

- CLI
![image](https://github.com/YaSuenag/SimpleCom/assets/1876302/34412494-eed7-4016-9167-9261e55fcb57)

**Comment by heartacker** [comment]
hi, @YaSuenag could you please release a version for me to test, thanks

**Comment by YaSuenag** [comment]
@heartacker 
I will not release any binaries for debugging. So please build yourself, or check attached images.
![スクリーンショット 2024-07-04 213554](https://github.com/YaSuenag/SimpleCom/assets/7421132/947e1731-05d1-45a6-9950-a24f420816c6)
![スクリーンショット 2024-07-04 213626](https://github.com/YaSuenag/SimpleCom/assets/7421132/1d6976d8-66c4-46eb-a55a-d226f7060dd0)

**Comment by heartacker** [comment]
we get this, Thanks
