### ISSUE TITLE
Is this possible to share current session to socket connect

### ISSUE THREAD

**Issue by heartacker** [YaSuenag/SimpleCom#47]
![image](https://github.com/YaSuenag/SimpleCom/assets/1876302/4cef3d64-3135-4730-a8d7-82ac7810e6b5)

**Comment by YaSuenag** [comment]
Do you mean mirror serial session to arbitrary TCP socket?
I do not agree with this idea so far.

Concept of SimpleCom is a "simple" serial terminal which can be integrated to Windows Terminal. And also I cannot imagine the usecase of port mirroring.

In case of TCP port mirroring in L2SW, it is useful for network troubleshooting. However this is a serial session, and SimpleCom assumes to communicate with (ascii) text, not binary. So we can observe everything that happens in serial session from the log `--log-file` or console output.
