### ISSUE TITLE
Accept command line parameters

### ISSUE THREAD

**Issue by ngbrown** [YaSuenag/SimpleCom#5]
It would be good to accept some command line parameters and connect straight away. Accept COM port number and baud rate directly at command line, and don't display dialog when parameters are passed.

Since most COM ports are now provided by USB devices, it may also be good to accept the USB Device ID in place of the COM port number.  Something in the format of `FTDIBUS\VID_0403+PID_6001+AH063JZ9A\0000`. Provide another command option that lists all the COM ports and their associated USB Device ID.

**Comment by ngbrown** [comment]
Added an additional idea about accepting the USB Device ID in place of the COM port number.

**Comment by YaSuenag** [comment]
> Added an additional idea about accepting the USB Device ID in place of the COM port number.

I cannot agree with it because serial port is not only USB device.

**Comment by ngbrown** [comment]
The idea was to have the command line take the COM port **"or"** accept the USB ID. I realize that not all COM ports are USB devices, but some are, and sometimes you want to connect to a specific device, even if the COM port number changed.

**Comment by YaSuenag** [comment]
I added this feature to upstream in bb8e413 . So I close this issue.
Please send PR if you want to work for further improvement.
