### ISSUE TITLE
F1 doesn't close program

### ISSUE THREAD

**Issue by ngbrown** [YaSuenag/SimpleCom#6]
The instructions in the readme were "Press F1 to leave its serial session and to finish SimpleCom". When F1 is pressed, a dialog is displayed prompting to leave the serial session. If "Yes" is selected, the program does not close and F1 no longer does anything.

The com port is not fully closed because characters can still be received, they just don't seem to be able to be sent.

**Comment by YaSuenag** [comment]
I cannot reproduce it on my Raspberry Pi 4.
What device did you use? Can you see SimpleCom process on task manager even if you pressed F1?

**Comment by ngbrown** [comment]
Yes, the SimpleCom process remains in the task manager and continues to receive characters, it just is no longer sending any characters. I am using a fairly standard USB-to-RS232 cable.

**Comment by YaSuenag** [comment]
I guess the problem is lack of detecting termination if stdin redirector were still receiving many data from peripheral.
I pushed new commit to add termination flag. Can you try it? It still works fine on my Raspberry Pi 2/4.

**Comment by ngbrown** [comment]
Between this and the high cpu issue, I was trying yesterday to reproduce it in Visual Studio, and it was no longer exhibiting any issues. It didn't even reproduce with the released binary...

**Comment by YaSuenag** [comment]
Hmm... I feel like there is also a problem with the serial device.

Anyway more information is needed to solve both #2 and this issue. I believe this issue has been gone since a18faeb38148f569758d5679b41792b816d1b088 .

**Comment by ngbrown** [comment]
With the solution I gave in #2, the F1 problem no longer exists. Without that CPU fix, your master branch now closes the program with F1.
