### ISSUE TITLE
Slashes in connection setup show as yen sign (¥)

### ISSUE THREAD

**Issue by ngbrown** [YaSuenag/SimpleCom#7]
![Screenshot - 2021-04-05_16-21-17](https://user-images.githubusercontent.com/228987/113638183-209f4100-962b-11eb-8185-e2ae44247a71.png)

Once connected, the title of the console window shows the slashes:

![Screenshot - 2021-04-05_16-23-04](https://user-images.githubusercontent.com/228987/113638244-40cf0000-962b-11eb-99cf-806abc7f9fb2.png)

I think the cause is the `MS UI Gothic` font is a Japanese only font, and not unicode. Setting the font to something like `MS Shell Dlg` might work better?

Or is yen sign separators normal for separating paths in Japan?

**Comment by ngbrown** [comment]
I did make a commit in my branch that replaced the whole resource file and marked it `LANGUAGE LANG_NEUTRAL, SUBLANG_SYS_DEFAULT`.  https://github.com/ngbrown/SimpleCom/commit/17a08672f5ae0aec8b719932bb9c45526ce85cde. My entire branch is [here](https://github.com/YaSuenag/SimpleCom/compare/master...ngbrown:patch-1?expand=1).

**Comment by YaSuenag** [comment]
> Or is yen sign separators normal for separating paths in Japan?

Yes, but it should be back slash.
Your change looks good. Can you send PR?

**Comment by YaSuenag** [comment]
@ngbrown I want to release new SimpleCom in near future, so I want to include your proposal in it. I want to merge PR from you to record your contribution. Can you do it?

**Comment by ngbrown** [comment]
@YaSuenag I've broken up my branch into multiple pull requests and if applicable, linked them the issues they addressed.
